spring:
  datasource:
    url: jdbc:h2:${external.mount}/db
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
external:
#  挂载路径 windows; end with '/'
  mount: D:/opt/sfs/
#  挂载路径 linux; end with '/'
#  mount: /opt/sfs/